apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-deployment
  namespace: example
spec:
  template:
    metadata:
      labels:
        app: app-deploy
    spec:
      containers:
        - name: application
          image: jeanpsv/kubernetes-simple-nodejs-example:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          args: ["npm", "start"]
          resources:
            requests:
              cpu: 200m
              memory: 1000Mi
            limits:
              cpu: 400m
              memory: 2000Mi
