apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: example
  labels:
    app: app-deploy
spec:
  selector:
    matchLabels:
      app: app-deploy
  template:
    metadata:
      labels:
        app: app-deploy
    spec:
      containers:
        - name: application
          image: andyshepherd/kubernetes-simple-nodejs:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          args: ["npm", "start"]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: MY_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: my_own_secret
