apiVersion: batch/v1
kind: Job
metadata:
  name: k6-performance-test
  namespace: example
spec:
  template:
    metadata:
      name: k6-performance-test
    spec:
      containers:
        - name: k6
          image: loadimpact/k6
          volumeMounts:
            - name: k6-script-test
              mountPath: /tmp/script.js
              subPath: script.js
          command: ["k6", "run", "/tmp/script.js"]
          env:
            - name: SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: k6-secret
                  key: hostname
      restartPolicy: Never
      volumes:
        - name: k6-script-test
          configMap:
            name: k6-script
